var N = null;var sourcesIndex = {};
sourcesIndex["cfg_if"] = {"name":"","files":["lib.rs"]};
sourcesIndex["form_urlencoded"] = {"name":"","files":["lib.rs"]};
sourcesIndex["hdfs"] = {"name":"","files":["err.rs","hdfs.rs","lib.rs","minidfs.rs","native.rs"]};
sourcesIndex["idna"] = {"name":"","files":["lib.rs","punycode.rs","uts46.rs"]};
sourcesIndex["lazy_static"] = {"name":"","files":["inline_lazy.rs","lib.rs"]};
sourcesIndex["libc"] = {"name":"","dirs":[{"name":"unix","dirs":[{"name":"bsd","dirs":[{"name":"apple","dirs":[{"name":"b64","dirs":[{"name":"x86_64","files":["align.rs","mod.rs"]}],"files":["mod.rs"]}],"files":["mod.rs"]}],"files":["mod.rs"]}],"files":["align.rs","mod.rs"]}],"files":["fixed_width_ints.rs","lib.rs","macros.rs"]};
sourcesIndex["log"] = {"name":"","files":["lib.rs","macros.rs"]};
sourcesIndex["matches"] = {"name":"","files":["lib.rs"]};
sourcesIndex["percent_encoding"] = {"name":"","files":["lib.rs"]};
sourcesIndex["tinyvec"] = {"name":"","dirs":[{"name":"array","files":["generated_impl.rs"]}],"files":["array.rs","arrayvec.rs","arrayvec_drain.rs","lib.rs","slicevec.rs","tinyvec.rs"]};
sourcesIndex["tinyvec_macros"] = {"name":"","files":["lib.rs"]};
sourcesIndex["unicode_bidi"] = {"name":"","dirs":[{"name":"char_data","files":["mod.rs","tables.rs"]}],"files":["deprecated.rs","explicit.rs","format_chars.rs","implicit.rs","level.rs","lib.rs","prepare.rs"]};
sourcesIndex["unicode_normalization"] = {"name":"","files":["__test_api.rs","decompose.rs","lib.rs","lookups.rs","no_std_prelude.rs","normalize.rs","perfect_hash.rs","quick_check.rs","recompose.rs","replace.rs","stream_safe.rs","tables.rs"]};
sourcesIndex["url"] = {"name":"","files":["host.rs","lib.rs","origin.rs","parser.rs","path_segments.rs","quirks.rs","slicing.rs"]};
createSourceSidebar();
